// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7oHj2YJER8gIn1uKjdTtDkA7NhVCCGE',
    appId: '1:888078756617:web:db387c1b0d1223d1e781d8',
    messagingSenderId: '888078756617',
    projectId: 'mooh-20804',
    authDomain: 'mooh-20804.firebaseapp.com',
    storageBucket: 'mooh-20804.firebasestorage.app',
    measurementId: 'G-9W0TEPEW85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOKGbJ2PNDIfDyXEQFcKzMsTFhDzM3oE',
    appId: '1:888078756617:android:df5ed86b423bc497e781d8',
    messagingSenderId: '888078756617',
    projectId: 'mooh-20804',
    storageBucket: 'mooh-20804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZS8bj0lJ5yUXL6KZ1vgxoPBmb9ogi-8',
    appId: '1:888078756617:ios:20e61fa6b15b1762e781d8',
    messagingSenderId: '888078756617',
    projectId: 'mooh-20804',
    storageBucket: 'mooh-20804.firebasestorage.app',
    iosClientId: '888078756617-agfl9ha7272r31uclstah345cjv6doh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mooh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZS8bj0lJ5yUXL6KZ1vgxoPBmb9ogi-8',
    appId: '1:888078756617:ios:20e61fa6b15b1762e781d8',
    messagingSenderId: '888078756617',
    projectId: 'mooh-20804',
    storageBucket: 'mooh-20804.firebasestorage.app',
    iosClientId: '888078756617-agfl9ha7272r31uclstah345cjv6doh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mooh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP7oHj2YJER8gIn1uKjdTtDkA7NhVCCGE',
    appId: '1:888078756617:web:4d5185aedbf4ad25e781d8',
    messagingSenderId: '888078756617',
    projectId: 'mooh-20804',
    authDomain: 'mooh-20804.firebaseapp.com',
    storageBucket: 'mooh-20804.firebasestorage.app',
    measurementId: 'G-H9ZXZCYHBE',
  );
}
